server:
  port: 8081

spring:
  application:
    name: back
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
product-messages:
  code-length: 8
  code-prefix: PROD-
  min-value: 0.0
  uuid-min-length: 9
  id-null-error: Product ID cannot be null
  name-null-error: Product name cannot be null
  name-empty-error: Product name cannot be empty
  negative-value-error: Product %s cannot be negative
  create-null-error: Product create request cannot be null
  update-null-error: Product update request cannot be null
auth-messages:
  account-create-null-error: Account create request cannot be null
  invalid-credentials: Invalid email or password
  username-null-error: Username cannot be null or empty
  firstname-null-error: FirstName cannot be null or empty
  email-null-error: Email cannot be null or empty
  password-null-error: Password cannot be null or empty
  password-length-error: Password must be at least 6 characters long
admin-auth-filter:
  email: admin@admin.com
  path: /products
  message: "Access denied: Only admin can perform this operation"
cart-messages:
  min-quantity: 1
  not-enough-stock: "Not enough stock available. Available: %d"
  product-out-of-stock: Product is out of stock
  quantity-must-be-positive: Quantity must be greater than 0
  no-authentication: No authentication found in security context
  user-null-error: User cannot be null
  cart-create-null-error: Add to cart request cannot be null
  cart-update-null-error: Update cart item request cannot be null
  product-null-error: Product ID cannot be null
wishlist-messages:
  request-null-error: Add to wishlist request cannot be null
  product-id-null-error: Add to wishlist request cannot be null

